### ISSUE TITLE
Add function `Dtz::to_wdl(halfmove_counter)`

### ISSUE THREAD

**Issue by KarelPeeters** [niklasf/shakmaty-syzygy#14]
First of all thanks for creating this crate!

I'm not super familiar with how exactly Syzygy tables work, but as far as I understand it should be possible to convert the combination of a `Dtz` value and the halfmove counter into a final WDL classification. Is there a function for this conversion somewhere in this crate?

Perhaps some combination of `from_dtz_after_zeroing` and `add_plies` works, but I'm not sure. I _think_ this function in the examples does what I want:

https://github.com/niklasf/shakmaty-syzygy/blob/c2cb4ada89d596aff2a67819cd75fb28feafdbd0/examples/fathom.rs#L23-L47

Would it be possible to add this to the main crate, maybe with the signature `Dtz::to_wdl(halfmove_counter)`?

**Comment by niklasf** [comment]
Unfortunately `Dtz::to_wdl(halfmove_counter)` is not uniquely defined due to DTZ rounding.

> Dtz(-n) can mean a loss in n + 1 plies and Dtz(n) can mean a win in n + 1 plies.

-- https://docs.rs/shakmaty-syzygy/0.17.0/shakmaty_syzygy/struct.Dtz.html

So the example follows the tablebase line until the end to decide the ambiguity in the context of the position. That's very expensive: There can be almost 100 steps on that way, and for each step we have to probe the positions after the legal moves in order to find the best move.

That procedure could be added as a library function, with some fair warnings about the cost.

I could also see the library more carefully distinguishing the ambiguity with types, something like `Dtz::to_ambiguous_wdl(halfmove_counter)` where the result is one of

```rust
enum AmbiguousWdl {
  Win,
  MaybeWin, // new case
  CursedWin,
  Draw,
  BlessedLoss,
  MaybeLoss, // new case
  Loss
}
```

**Comment by KarelPeeters** [comment]
Ah, I took the following sentence in that quote to mean that there is no rounding if it would change the result:

> Rounding is never used for endgame phases where it would change the game theoretical outcome.

What does that mean then?

I didn't even see the recursion in the example I linked, that can get very expensive indeed. Is there no way to cheaply get the WDL of a position with a non-zero move counter from the Syzygy tables? Doesn't every chess engine that uses them want to do this as the main use case? Of course there is `probe_wdl` but that only works for positions with a zero-move counter.

**Comment by niklasf** [comment]
It's tricky.

> Is there no way to cheaply get the WDL of a position with a non-zero move counter from the Syzygy tables?

Indeed no, in general. Let me try to explain ...

> Doesn't every chess engine that uses them want to do this as the main use case? Of course there is probe_wdl but that only works for positions with a zero-move counter.

The only way to cross from non-tablebase territory to tablebase territory is with a capture. So initially the halfmove counter is always zero, and we can efficiently get the WDL, and the tablebase mainline guarantees that outcome. In endgames where it does not matter ("Rounding is never used for endgame phases where it would change the game theoretical outcome"), DTZ values may be stored rounded, and the tablebase mainline may waste up to 1 ply.

So an easy and correct strategy for engines is to always immediately follow the tablebase line.

A trickier, but also correct strategy (for example used by Stockfish), is to use the engine's own search only while DTZ + halfmove counter indicates that it's safe to waste 2 plies. Then follow the tablebase line.

So ...

> Rounding is never used for endgame phases where it would change the game theoretical outcome.

referring to an endgame phase, always reached with halfmove counter 0, but

> [...] some primary tablebase lines may waste up to 1 ply. [...]
>
> This means users need to be careful in positions that are nearly drawn under the 50-move rule! Carelessly wasting 1 more ply by not following the tablebase recommendation, for a total of 2 wasted plies, may change the outcome of the game.

**Comment by niklasf** [comment]
Refactored public APIs to make sure DTZ rounding is properly dealt with or at least acknowleged and introduced `AmbiguousWdl::from_dtz_and_halfmoves(dtz: MaybeRounded<Dtz>, halfmoves: u32)`.

I decided not to add a function to recursively resolve the ambiguity and also removed this from the example.

**Comment by KarelPeeters** [comment]
Sorry it took me a while to get back to this, there are some difficult concepts to understand here!

Only looking into the tablebase when a capture has just happened makes sense during tree search, and even makes things faster since less lookups happen.

I'm still not sure about when an engine can do when it receives a unknown board position with at least one move after the last capture. This can happen for two reasons, either the user is just analyzing a random position or the opponent is not following the same tablebase line you are. 

I assume I can still get the best move from the tablebase, since the halfmove counter has no effect on that. To get the real WDL value I imagine it's a good idea to first look at the `AmbiguousWdl` value. In cases where that is ambiguous does following the best move until the end of the game still make sense?

**Comment by niklasf** [comment]
The tablebase mainline can waste up to 1 ply, unless doing so would change the outcome starting from a capture or pawn move.

If we waste 1 more ply by deviating from the mainline, for a total of 2 wasted plies, the result may change, in rare situations. If our opponent blunders from a drawn position into a loss 1 ply short of drawing, this may cancel out and the tablebase mainline will fail to convert the advantage, in rare situations.

I know that's disappointing, but the following guarantees is what the creator of the tablebases mostly cared about:

* If we would be winning against best play, starting from a capture, then following the tablebase recommendations will definitely win, no matter what the opponent does (even if they deviate from the tablebase mainline).
* If we would be drawing against best play, starting from a capture, then following the tablebase recommendations will definitely not lose (no matter what the opponent tries).

Both hold with and without 50-move rule.

The ambiguous cases from custom starting positions are rare. Basically these options exist:
* For the tablebase explorer on Lichess, I simply chose to show the ambiguity in the UI. For example, "Win or 50-moves by prior mistake" on https://lichess.org/analysis/fromPosition/k7/8/8/8/8/8/8/5KBN_w_-_-_42_1.
* Crossing your fingers and following the tablebase recommendations like the deleted example is also not unreasonable, but not perfect.
* The best is to keep alpha-beta searching to resolve the ambiguity. The branching factor is low, because not many moves will stay right on the edge of ambiguity.

**Comment by KarelPeeters** [comment]
Your last response definitely clarifies a lot! Looks like I was misunderstanding the information tablebases actually contained! I'll spend some time playing around with these edge case positions to get more familiar with them.

Thanks a lot for all of the help!
