### ISSUE TITLE
Get the set of loaded `Material`s.

### ISSUE THREAD

**Issue by KarelPeeters** [niklasf/shakmaty-syzygy#15]
### Suggestion

Add a function similar to `TableBase::loaded_materials(&self) -> impl Iterator<Material>` that returns all of keys that exist in the `wdl` and `dtz` hashmaps.

### Motivation

I'm writing a chess engine, and I'm not using shakmaty for the board format. (Currently I'm using the `chess` crate but I'll probably switch to my own implementation in the future). It would be great if I could just quickly check whether a position is in the tablebase before I spent time converting it to shakmaty's board representation.

Of course I can keep track of which files I put in the tablebase and parse their names myself, but this crate already does that and it seems like it's not too hard to expose that information.

**Comment by niklasf** [comment]
Not opposed to adding this, but maybe it's simpler to expose the maximum number of pieces of any loaded table? Using a full set up to some piece count is by far the most common case, so it might make sense to optimistically assume it is complete.

Checking for a single table to be present also makes an optimistic assumption. That's because tables reachable via captures and promotions may be required (recursively). So for example, to be able to query all KPvK positions, KQvK is also required.

**Comment by KarelPeeters** [comment]
Indeed that makes a lot more sense, looks like I was over-complicating things. Thanks for adding the function!
